environment:
  matrix:
    - nodejs_version: '10'

install:
  - ps: >
      if ($env:nodejs_version -eq "10") {
        Install-Product node $env:nodejs_version x64
      } else {
        Install-Product node $env:nodejs_version
      }
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - cd node_modules
  - cd playwright-core
  - npm install --save rimraf@3.0.1
  - cd ..
  - cd ..

matrix:
  fast_finish: false
build: off
shallow_clone: true
test_script:
  - node --version
  - npm --version
  - npx --version
  - npm run build
  - npm test
cache:
  - '%APPDATA%\npm-cache'
