name: TestsPipeline
on: [push]
concurrency:
  group: TestsPipeline
  cancel-in-progress: true
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Install linux dependencies needed by browsers in headfull mode
        run: |
          sudo apt-get update
          sudo apt-get install libegl1\
              libopus0\
              libwoff1\
              libharfbuzz-icu0\
              gstreamer1.0-plugins-base\
              libgstreamer-gl1.0-0\
              gstreamer1.0-plugins-bad\
              libopenjp2-7\
              libwebpdemux2\
              libenchant-2-2\
              libhyphen0\
              libgles2\
              libevdev2\
              gstreamer1.0-libav
      - name: Setup node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: node --version
      - run: npm --version
      - name: Install playwrigh-fluent
        run: npm ci
      - name: Install system dependencies for Playwright
        run: npx playwright install-deps
      - name: Install playwright v1.29.1
        run: npm install --no-save playwright@1.29.1
      - name: Install microsoft-edge
        run: npx playwright install msedge --with-deps
      - name: Build
        run: npm run build
      - name: Run tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm test
      - run: echo "🍏 This job's status is ${{ job.status }}."
  Windows:
    runs-on: windows-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Setup node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: node --version
      - run: npm --version
      - name: Install playwrigh-fluent
        run: npm ci
      - name: Install playwright v1.29.1
        run: npm install --no-save playwright@1.29.1
      - name: Install microsoft-edge
        run: npx playwright install msedge --with-deps
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm test
      - run: echo "🍏 This job's status is ${{ job.status }}."
