name: Internal Tests
on: [push]
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: node --version
      - run: npm --version
      - name: Install playwright v1.12.2 peer dependency
        run: npm install --no-save playwright@1.12.2
      - name: Install playwrigh-fluent
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm test
      - run: echo "🍏 This job's status is ${{ job.status }}."
